### ISSUE TITLE
NEXT TODO

### ISSUE THREAD

**Issue by aasumitro** [bakode/exp-react-lc#1]
1. Agent with Multi Group/Organization (*if possible)
2. Transfer Chat to Group/Personal
3. Implement Rich Message

**Comment by aasumitro** [comment]
# Agent with Multi Group/Organization (*if possible)
- [ ] CREATE ACCOUNT FROM BACKEND WITH SPECIFIED SETTINGS
- [ ] STORE CREDENTIALS DATA
- [ ] LOGIN USER
- [ ] .....

**Comment by aasumitro** [comment]
# Transfer Chat to Group/Personal
- [x] ... (self-transfer: for pick from the queue, selected agent transfer for assignment)

**Comment by aasumitro** [comment]
# Implement Rich Message 
- [x] ... *(using custom message payload)
